-- =========================================================================
-- DATABASE SETUP & SEED DATA SUPABASE - WEB DESA TAJEMSARI TEGOWANU
-- Copy & Paste skrip ini di Supabase Dashboard -> SQL Editor -> Klik "RUN"
-- Versi: 100% Auto-Migration (Semua Kolom Ditambahkan Otomatis Tanpa Error)
-- =========================================================================

-- 1. TABEL ADMIN USERS (LOGIN PENGURUS/ADMIN DESA)
CREATE TABLE IF NOT EXISTS public.admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  nama_lengkap TEXT,
  email TEXT,
  role TEXT DEFAULT 'Admin Utama',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. TABEL HERO SECTION & SAMBUTAN KEPALA DESA (BERANDA UTAMA)
CREATE TABLE IF NOT EXISTS public.hero_section (
  id INT PRIMARY KEY DEFAULT 1,
  badge TEXT,
  judul TEXT NOT NULL,
  deskripsi TEXT,
  bg_image TEXT DEFAULT '',
  kades_nama TEXT,
  kades_jabatan TEXT,
  kades_periode TEXT,
  kades_foto TEXT DEFAULT '',
  kades_sambutan TEXT,
  stat_penduduk TEXT,
  stat_rt_rw TEXT,
  stat_umkm TEXT,
  cta_primary TEXT DEFAULT 'Profil Desa Tajemsari',
  cta_primary_link TEXT DEFAULT 'profil',
  cta_secondary TEXT DEFAULT 'Potensi & Wisata Desa',
  cta_secondary_link TEXT DEFAULT 'potensi',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Pastikan semua kolom hero_section ada jika tabel sudah pernah dibuat sebelumnya
ALTER TABLE public.hero_section ADD COLUMN IF NOT EXISTS cta_primary TEXT DEFAULT 'Profil Desa Tajemsari';
ALTER TABLE public.hero_section ADD COLUMN IF NOT EXISTS cta_primary_link TEXT DEFAULT 'profil';
ALTER TABLE public.hero_section ADD COLUMN IF NOT EXISTS cta_secondary TEXT DEFAULT 'Potensi & Wisata Desa';
ALTER TABLE public.hero_section ADD COLUMN IF NOT EXISTS cta_secondary_link TEXT DEFAULT 'potensi';
ALTER TABLE public.hero_section ADD COLUMN IF NOT EXISTS bg_image TEXT DEFAULT '';
ALTER TABLE public.hero_section ADD COLUMN IF NOT EXISTS kades_foto TEXT DEFAULT '';
ALTER TABLE public.hero_section ADD COLUMN IF NOT EXISTS kades_nama TEXT;
ALTER TABLE public.hero_section ADD COLUMN IF NOT EXISTS kades_jabatan TEXT;
ALTER TABLE public.hero_section ADD COLUMN IF NOT EXISTS kades_periode TEXT;
ALTER TABLE public.hero_section ADD COLUMN IF NOT EXISTS kades_sambutan TEXT;
ALTER TABLE public.hero_section ADD COLUMN IF NOT EXISTS stat_penduduk TEXT;
ALTER TABLE public.hero_section ADD COLUMN IF NOT EXISTS stat_rt_rw TEXT;
ALTER TABLE public.hero_section ADD COLUMN IF NOT EXISTS stat_umkm TEXT;

-- 3. TABEL PROFIL DESA (SEJARAH, VISI & MISI, PERANGKAT DESA)
CREATE TABLE IF NOT EXISTS public.profil_desa (
  id INT PRIMARY KEY DEFAULT 1,
  sejarah_judul TEXT,
  sejarah_paragraf1 TEXT,
  sejarah_paragraf2 TEXT,
  visi_judul TEXT,
  visi_deskripsi TEXT,
  misi_list JSONB DEFAULT '[]'::jsonb,
  perangkat_list JSONB DEFAULT '[]'::jsonb,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Pastikan semua kolom profil_desa ada jika tabel sudah pernah dibuat sebelumnya
ALTER TABLE public.profil_desa ADD COLUMN IF NOT EXISTS sejarah_judul TEXT;
ALTER TABLE public.profil_desa ADD COLUMN IF NOT EXISTS sejarah_paragraf1 TEXT;
ALTER TABLE public.profil_desa ADD COLUMN IF NOT EXISTS sejarah_paragraf2 TEXT;
ALTER TABLE public.profil_desa ADD COLUMN IF NOT EXISTS visi_judul TEXT;
ALTER TABLE public.profil_desa ADD COLUMN IF NOT EXISTS visi_deskripsi TEXT;
ALTER TABLE public.profil_desa ADD COLUMN IF NOT EXISTS misi_list JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.profil_desa ADD COLUMN IF NOT EXISTS perangkat_list JSONB DEFAULT '[]'::jsonb;

-- 4. TABEL BERITA & PUBLIKASI DESA
CREATE TABLE IF NOT EXISTS public.berita (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  judul TEXT NOT NULL,
  slug TEXT,
  kategori TEXT,
  penulis TEXT,
  tanggal DATE DEFAULT CURRENT_DATE,
  ringkasan TEXT,
  isi TEXT,
  gambar TEXT DEFAULT '',
  galeri JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Pastikan semua kolom berita ada jika tabel sudah pernah dibuat sebelumnya
ALTER TABLE public.berita ADD COLUMN IF NOT EXISTS slug TEXT;
ALTER TABLE public.berita ADD COLUMN IF NOT EXISTS kategori TEXT;
ALTER TABLE public.berita ADD COLUMN IF NOT EXISTS penulis TEXT;
ALTER TABLE public.berita ADD COLUMN IF NOT EXISTS tanggal DATE DEFAULT CURRENT_DATE;
ALTER TABLE public.berita ADD COLUMN IF NOT EXISTS ringkasan TEXT;
ALTER TABLE public.berita ADD COLUMN IF NOT EXISTS isi TEXT;
ALTER TABLE public.berita ADD COLUMN IF NOT EXISTS gambar TEXT DEFAULT '';
ALTER TABLE public.berita ADD COLUMN IF NOT EXISTS galeri JSONB DEFAULT '[]'::jsonb;

-- 5. TABEL PRODUK & MULTI-USAHA UMKM DESA
CREATE TABLE IF NOT EXISTS public.umkm (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_produk TEXT NOT NULL,
  kategori TEXT,
  pembuat TEXT,
  dusun TEXT DEFAULT 'Dusun Kendalsari, RT 02 / RW 01',
  harga TEXT,
  wa_seller TEXT,
  deskripsi TEXT,
  gambar TEXT DEFAULT '',
  produk_list JSONB DEFAULT '[]'::jsonb,
  galeri JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Pastikan semua kolom umkm ada jika tabel sudah pernah dibuat sebelumnya
ALTER TABLE public.umkm ADD COLUMN IF NOT EXISTS kategori TEXT;
ALTER TABLE public.umkm ADD COLUMN IF NOT EXISTS pembuat TEXT;
ALTER TABLE public.umkm ADD COLUMN IF NOT EXISTS dusun TEXT DEFAULT 'Dusun Kendalsari, RT 02 / RW 01';
ALTER TABLE public.umkm ADD COLUMN IF NOT EXISTS harga TEXT;
ALTER TABLE public.umkm ADD COLUMN IF NOT EXISTS wa_seller TEXT;
ALTER TABLE public.umkm ADD COLUMN IF NOT EXISTS deskripsi TEXT;
ALTER TABLE public.umkm ADD COLUMN IF NOT EXISTS gambar TEXT DEFAULT '';
ALTER TABLE public.umkm ADD COLUMN IF NOT EXISTS produk_list JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.umkm ADD COLUMN IF NOT EXISTS galeri JSONB DEFAULT '[]'::jsonb;

-- 6. TABEL DESTINASI WISATA DESA
CREATE TABLE IF NOT EXISTS public.wisata (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_tempat TEXT NOT NULL,
  kategori TEXT,
  lokasi TEXT,
  jam_buka TEXT,
  tiket_masuk TEXT,
  deskripsi TEXT,
  gambar TEXT DEFAULT '',
  galeri JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Pastikan semua kolom wisata ada jika tabel sudah pernah dibuat sebelumnya
ALTER TABLE public.wisata ADD COLUMN IF NOT EXISTS kategori TEXT;
ALTER TABLE public.wisata ADD COLUMN IF NOT EXISTS lokasi TEXT;
ALTER TABLE public.wisata ADD COLUMN IF NOT EXISTS jam_buka TEXT;
ALTER TABLE public.wisata ADD COLUMN IF NOT EXISTS tiket_masuk TEXT;
ALTER TABLE public.wisata ADD COLUMN IF NOT EXISTS deskripsi TEXT;
ALTER TABLE public.wisata ADD COLUMN IF NOT EXISTS gambar TEXT DEFAULT '';
ALTER TABLE public.wisata ADD COLUMN IF NOT EXISTS galeri JSONB DEFAULT '[]'::jsonb;

-- 7. TABEL INFORMASI FOOTER & KONTAK
CREATE TABLE IF NOT EXISTS public.footer_info (
  id INT PRIMARY KEY DEFAULT 1,
  alamat TEXT,
  telepon TEXT,
  whatsapp TEXT,
  email TEXT,
  jam_pelayanan TEXT,
  maps_url TEXT,
  facebook TEXT,
  instagram TEXT,
  youtube TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Pastikan semua kolom footer_info ada jika tabel sudah pernah dibuat sebelumnya
ALTER TABLE public.footer_info ADD COLUMN IF NOT EXISTS alamat TEXT;
ALTER TABLE public.footer_info ADD COLUMN IF NOT EXISTS telepon TEXT;
ALTER TABLE public.footer_info ADD COLUMN IF NOT EXISTS whatsapp TEXT;
ALTER TABLE public.footer_info ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE public.footer_info ADD COLUMN IF NOT EXISTS jam_pelayanan TEXT;
ALTER TABLE public.footer_info ADD COLUMN IF NOT EXISTS maps_url TEXT;
ALTER TABLE public.footer_info ADD COLUMN IF NOT EXISTS facebook TEXT;
ALTER TABLE public.footer_info ADD COLUMN IF NOT EXISTS instagram TEXT;
ALTER TABLE public.footer_info ADD COLUMN IF NOT EXISTS youtube TEXT;

-- 8. TABEL PENGATURAN WEBSITE & RUNNING TEXT
CREATE TABLE IF NOT EXISTS public.website_settings (
  id INT PRIMARY KEY DEFAULT 1,
  nama_desa TEXT,
  kecamatan TEXT,
  kabupaten TEXT,
  provinsi TEXT,
  email_admin TEXT,
  telepon_kantor TEXT,
  running_text TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Pastikan semua kolom website_settings ada jika tabel sudah pernah dibuat sebelumnya
ALTER TABLE public.website_settings ADD COLUMN IF NOT EXISTS nama_desa TEXT;
ALTER TABLE public.website_settings ADD COLUMN IF NOT EXISTS kecamatan TEXT;
ALTER TABLE public.website_settings ADD COLUMN IF NOT EXISTS kabupaten TEXT;
ALTER TABLE public.website_settings ADD COLUMN IF NOT EXISTS provinsi TEXT;
ALTER TABLE public.website_settings ADD COLUMN IF NOT EXISTS email_admin TEXT;
ALTER TABLE public.website_settings ADD COLUMN IF NOT EXISTS telepon_kantor TEXT;
ALTER TABLE public.website_settings ADD COLUMN IF NOT EXISTS running_text TEXT;

-- 9. TABEL PERMOHONAN SURAT & LAYANAN WARGA
CREATE TABLE IF NOT EXISTS public.permohonan_surat (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nomor_tiket TEXT UNIQUE,
  nama_warga TEXT NOT NULL,
  nik TEXT NOT NULL,
  no_hp TEXT,
  alamat_lengkap TEXT,
  jenis_surat TEXT NOT NULL,
  keperluan TEXT,
  status TEXT DEFAULT 'Menunggu',
  catatan_admin TEXT,
  tanggal_pengajuan TEXT,
  file_surat_url TEXT DEFAULT '',
  file_surat_name TEXT DEFAULT '',
  metode_pengambilan TEXT DEFAULT 'Digital',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Pastikan semua kolom permohonan_surat ada jika tabel sudah pernah dibuat sebelumnya
ALTER TABLE public.permohonan_surat ADD COLUMN IF NOT EXISTS nomor_tiket TEXT;
ALTER TABLE public.permohonan_surat ADD COLUMN IF NOT EXISTS nama_warga TEXT;
ALTER TABLE public.permohonan_surat ADD COLUMN IF NOT EXISTS nik TEXT;
ALTER TABLE public.permohonan_surat ADD COLUMN IF NOT EXISTS no_hp TEXT;
ALTER TABLE public.permohonan_surat ADD COLUMN IF NOT EXISTS alamat_lengkap TEXT;
ALTER TABLE public.permohonan_surat ADD COLUMN IF NOT EXISTS jenis_surat TEXT;
ALTER TABLE public.permohonan_surat ADD COLUMN IF NOT EXISTS keperluan TEXT;
ALTER TABLE public.permohonan_surat ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Menunggu';
ALTER TABLE public.permohonan_surat ADD COLUMN IF NOT EXISTS catatan_admin TEXT;
ALTER TABLE public.permohonan_surat ADD COLUMN IF NOT EXISTS tanggal_pengajuan TEXT;
ALTER TABLE public.permohonan_surat ADD COLUMN IF NOT EXISTS file_surat_url TEXT DEFAULT '';
ALTER TABLE public.permohonan_surat ADD COLUMN IF NOT EXISTS file_surat_name TEXT DEFAULT '';
ALTER TABLE public.permohonan_surat ADD COLUMN IF NOT EXISTS metode_pengambilan TEXT DEFAULT 'Digital';

-- =========================================================================
-- KETENTUAN ROW LEVEL SECURITY (RLS) - AKSES PUBLIK READ & WRITE
-- =========================================================================
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hero_section ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profil_desa ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.berita ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.umkm ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wisata ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.permohonan_surat ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.footer_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.website_settings ENABLE ROW LEVEL SECURITY;

-- Drop Policy jika sudah ada sebelumnya agar tidak terjadi duplikasi error
DROP POLICY IF EXISTS "Public Admin Users" ON public.admin_users;
DROP POLICY IF EXISTS "Public Hero Section" ON public.hero_section;
DROP POLICY IF EXISTS "Public Profil Desa" ON public.profil_desa;
DROP POLICY IF EXISTS "Public Berita" ON public.berita;
DROP POLICY IF EXISTS "Public UMKM" ON public.umkm;
DROP POLICY IF EXISTS "Public Wisata" ON public.wisata;
DROP POLICY IF EXISTS "Public Permohonan Surat" ON public.permohonan_surat;
DROP POLICY IF EXISTS "Public Footer Info" ON public.footer_info;
DROP POLICY IF EXISTS "Public Website Settings" ON public.website_settings;

-- Buat Ulang Policy (Akses Penuh Publik & Admin CMS)
CREATE POLICY "Public Admin Users" ON public.admin_users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Hero Section" ON public.hero_section FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Profil Desa" ON public.profil_desa FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Berita" ON public.berita FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public UMKM" ON public.umkm FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Wisata" ON public.wisata FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Permohonan Surat" ON public.permohonan_surat FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Footer Info" ON public.footer_info FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Website Settings" ON public.website_settings FOR ALL USING (true) WITH CHECK (true);

-- =========================================================================
-- SEED DATA AWAL BERSIH (TANPA GAMBAR DUMMY UNSPLASH)
-- =========================================================================

-- 1. Seed Credentials Admin (Dua opsi login aktif)
INSERT INTO public.admin_users (username, password, nama_lengkap, email, role)
VALUES 
  ('admin', 'admin123', 'Administrator Utama', 'admin@tajemsari.desa.id', 'Admin Utama'),
  ('admin@tajemsari.desa.id', 'tajemsari2026', 'Admin Desa Tajemsari', 'admin@tajemsari.desa.id', 'Admin Utama')
ON CONFLICT (username) DO UPDATE SET password = EXCLUDED.password;

-- 2. Seed Hero Section & Sambutan Kepala Desa
INSERT INTO public.hero_section (id, badge, judul, deskripsi, bg_image, kades_nama, kades_jabatan, kades_periode, kades_foto, kades_sambutan, stat_penduduk, stat_rt_rw, stat_umkm, cta_primary, cta_primary_link, cta_secondary, cta_secondary_link)
VALUES (
  1,
  'Website Resmi Desa Tajemsari • Kec. Tegowanu',
  'Selamat Datang di Portal Resmi Desa Tajemsari',
  'Desa Tajemsari merupakan desa paling barat di Kecamatan Tegowanu, Kabupaten Grobogan, Jawa Tengah. Wilayah desa ini terdiri dari 4 dusun: Kendalsari, Mlangi, Plosorejo, dan Tajem.',
  '',
  'H. Suhartono, S.Sos',
  'Kepala Desa Tajemsari Tegowanu',
  'Periode 2021 - 2027',
  '',
  'Assalamu’alaikum Warahmatullahi Wabarakatuh. Selamat datang warga dan tamu Desa Tajemsari, Kecamatan Tegowanu. Peluncuran website resmi ini merupakan wujud transparansi, keterbukaan informasi publik, serta kemudahan akses potensi desa agrowisata dan UMKM.',
  '2.845 Jiwa',
  '4 RT / 2 RW',
  '12 UMKM',
  'Profil Desa Tajemsari',
  'profil',
  'Potensi & Wisata Desa',
  'potensi'
) ON CONFLICT (id) DO UPDATE SET
  judul = EXCLUDED.judul,
  deskripsi = EXCLUDED.deskripsi,
  kades_nama = EXCLUDED.kades_nama,
  kades_sambutan = EXCLUDED.kades_sambutan,
  bg_image = EXCLUDED.bg_image,
  kades_foto = EXCLUDED.kades_foto,
  cta_primary = EXCLUDED.cta_primary,
  cta_primary_link = EXCLUDED.cta_primary_link,
  cta_secondary = EXCLUDED.cta_secondary,
  cta_secondary_link = EXCLUDED.cta_secondary_link;

-- 3. Seed Profil Desa & Perangkat Desa
INSERT INTO public.profil_desa (id, sejarah_judul, sejarah_paragraf1, sejarah_paragraf2, visi_judul, visi_deskripsi, misi_list, perangkat_list)
VALUES (
  1,
  'Sejarah Singkat Desa Tajemsari',
  'Nama Desa Tajemsari berasal dari gabungan kata "Tajem" yang bermakna tajam/tegas dalam memegang prinsip kebenaran, serta "Sari" yang berarti inti kebaikan dan keasrian alam.',
  'Dengan hamparan persawahan seluas lebih dari 340 hektar dan sistem irigasi teknis yang terjaga, Tajemsari kini bertransformasi menjadi desa agrowisata mandiri.',
  '"Mewujudkan Desa Tajemsari yang Mandiri, Sejahtera, Transparan, dan Berorientasi Agrowisata Ramah Lingkungan."',
  'Fokus utama pada penguatan ketahanan pangan lokal, kemudahan akses informasi warga, serta pemberdayaan ekonomi UMKM Tajemsari.',
  '["Meningkatkan kualitas pelayanan administrasi desa yang cepat, ramah, dan transparan.", "Mengembangkan infrastruktur jalan tani dan saluran irigasi persawahan Tegowanu.", "Mendukung pemasaran digital produk UMKM lokal Madu Klanceng, Kopi Robusta, dan Kerajinan Anyaman Bambu."]'::jsonb,
  '[{"id":1,"nama":"H. Suhartono, S.Sos","jabatan":"Kepala Desa Tajemsari","foto":""},{"id":2,"nama":"Bambang Wijaya, S.T","jabatan":"Sekretaris Desa","foto":""},{"id":3,"nama":"Siti Rahmawati, S.E","jabatan":"Kaur Keuangan","foto":""},{"id":4,"nama":"Sri Rejeki, A.Md","jabatan":"Kasi Kesejahteraan","foto":""}]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  sejarah_judul = EXCLUDED.sejarah_judul,
  sejarah_paragraf1 = EXCLUDED.sejarah_paragraf1,
  sejarah_paragraf2 = EXCLUDED.sejarah_paragraf2,
  visi_judul = EXCLUDED.visi_judul,
  visi_deskripsi = EXCLUDED.visi_deskripsi,
  misi_list = EXCLUDED.misi_list,
  perangkat_list = EXCLUDED.perangkat_list;

-- 4. Seed Berita Desa Awal (Gambar Kosong)
INSERT INTO public.berita (id, judul, slug, kategori, penulis, tanggal, ringkasan, isi, gambar, galeri)
VALUES 
(
  1,
  'Penyaluran BLT Dana Desa Tajemsari Tahap III Berjalan Lancar',
  'blt-tahap-3',
  'Ekonomi',
  'Sekretariat Desa Tajemsari',
  '2026-07-26',
  'Pemerintah Desa Tajemsari menyerahkan bantuan langsung tunai kepada 45 keluarga penerima manfaat secara transparan.',
  'Pemerintah Desa Tajemsari, Kecamatan Tegowanu, Kabupaten Grobogan telah menyalurkan Bantuan Langsung Tunai (BLT) Dana Desa Tahap III Tahun 2026. Penyerahan bantuan ini dilaksanakan di Balai Desa Tajemsari dengan mengedepankan asas akuntabilitas dan tepat sasaran bagi warga terdaftar.\n\nDalam kesempatan tersebut, Kepala Desa Tajemsari H. Suhartono menyampaikan harapan agar bantuan tunai ini dapat meringankan beban ekonomi warga serta dimanfaatkan untuk kebutuhan pokok sehari-hari keluarga.\n\nProses verifikasi data dilakukan secara berlapis oleh tim Kasi Kesejahteraan Desa untuk memastikan tidak ada duplikasi data penerima bantuan sosial.',
  '',
  '[]'::jsonb
),
(
  2,
  'Panen Raya Padi Organik Kelompok Tani Tajemsari Makmur',
  'panen-raya-padi-organik',
  'Pertanian',
  'Kasi Kesejahteraan',
  '2026-07-20',
  'Para petani Tajemsari berhasil meningkatkan produktivitas panen berkat pola pertanian ramah lingkungan.',
  'Kelompok Tani Tajemsari Makmur Tegowanu merayakan panen raya padi organik. Berdasarkan ubinan bersama dinas pertanian Grobogan, hasil panen mengalami kenaikan 18% dibandingkan musim tanam lalu. Petani Tajemsari optimis mewujudkan kemandirian pangan desa.\n\nBupati Grobogan turut mengapresiasi inovasi penggunaan pupuk hijau cair buatan swadaya petani Tajemsari yang terbukti menekan biaya operasional penanaman hingga 30%.\n\nPemasaran hasil panen padi organik Tajemsari nantinya akan disalurkan melalui BUMDes Tajemsari dan platform UMKM lokal.',
  '',
  '[]'::jsonb
),
(
  3,
  'Posyandu Balita & Lansia Terpadu Tajemsari Tegowanu',
  'posyandu-balita-dan-lansia',
  'Kesehatan',
  'Kader Kesehatan Desa',
  '2026-07-12',
  'Pemeriksaan kesehatan gratis, imunisasi balita, dan senam lansia digelar rutin di Balai Desa.',
  'Kader Kesehatan Desa Tajemsari bekerjasama dengan Puskesmas Tegowanu menyelenggarakan Posyandu Balita dan Posbindu Lansia. Kegiatan meliputi pemberian makanan tambahan (PMT), imunisasi, dan skrining kesehatan rutin bagi masyarakat.',
  '',
  '[]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  judul = EXCLUDED.judul,
  ringkasan = EXCLUDED.ringkasan,
  isi = EXCLUDED.isi,
  gambar = EXCLUDED.gambar,
  galeri = EXCLUDED.galeri;

-- 5. Seed Multi-Produk & Multi-Usaha UMKM Desa (Gambar Kosong)
INSERT INTO public.umkm (id, nama_produk, kategori, pembuat, dusun, harga, wa_seller, deskripsi, gambar, produk_list, galeri)
VALUES 
(
  1,
  'Usaha Madu Klanceng & Olahan Lebah Pak Warsito',
  'Kuliner',
  'Pak Warsito',
  'Dusun Kendalsari, RT 02 / RW 01',
  'Mulai Rp 20.000',
  '6281234567890',
  'Peternakan lebah klanceng alami binaan Desa Tajemsari. Memproduksi aneka varian madu murni, sarang lebah (honeycomb), propolis cair, dan sabun madu alami tanpa pengawet buatan.',
  '',
  '[{"id":"p1_1","nama":"Madu Klanceng Murni 500ml","harga":"Rp 85.000","gambar":"","deskripsi":"Madu klanceng murni botol kaca 500ml dengan rasa manis-asam segar kaya antioksidan alami."},{"id":"p1_2","nama":"Sarang Madu Asli (Honeycomb) 250gr","harga":"Rp 60.000","gambar":"","deskripsi":"Potongan sarang lebah asli berisi madu segar yang bisa dikunyah langsung."},{"id":"p1_3","nama":"Propolis Cair Alami Tajem 30ml","harga":"Rp 45.000","gambar":"","deskripsi":"Ekstrak propolis konsentrat untuk meningkatkan imunitas tubuh dan daya tahan fisik."},{"id":"p1_4","nama":"Sabun Herbal Madu & Zaitun","harga":"Rp 20.000","gambar":"","deskripsi":"Sabun mandi batang alami dari sari madu klanceng untuk melembabkan kulit."}]'::jsonb,
  '[]'::jsonb
),
(
  2,
  'Kopi Robusta & Produk Olahan Ibu Tani',
  'Kuliner',
  'Kelompok Usaha Ibu Tani',
  'Dusun Tajem, RT 01 / RW 02',
  'Mulai Rp 15.000',
  '6281234567891',
  'Sentra olahan biji kopi lokal dan camilan pendamping hasil panen sawah. Menyediakan kopi bubuk sangrai tradisional, biji kopi roast, dan keripik tempe kedelai gurih renyah.',
  '',
  '[{"id":"p2_1","nama":"Kopi Robusta Sawah Tajem 250gr","harga":"Rp 25.000","gambar":"","deskripsi":"Kopi bubuk robusta sangrai arang dengan aroma wangi dan rasa mantap."},{"id":"p2_2","nama":"Roasted Coffee Beans (Biji Sangrai) 500gr","harga":"Rp 50.000","gambar":"","deskripsi":"Biji kopi sangrai kualitas medium roast untuk penikmat kopi manual brew."},{"id":"p2_3","nama":"Keripik Tempe Kedelai Gurih Tajemsari","harga":"Rp 15.000","gambar":"","deskripsi":"Keripik tempe renyah dengan bumbu ketumbar dan daun jeruk alami."}]'::jsonb,
  '[]'::jsonb
),
(
  3,
  'Kerajinan Anyaman Bambu & Mebel Mbah Pawiro',
  'Kerajinan',
  'Mbah Pawiro',
  'Dusun Mlangi, RT 03 / RW 01',
  'Mulai Rp 35.000',
  '6281234567892',
  'Pengrajin anyaman bambu legendaris Desa Tajemsari. Memproduksi aneka perabot dapur tradisional, tampah beras, keranjang buah, besek kenduri, serta kursi santai bambu.',
  '',
  '[{"id":"p3_1","nama":"Tampah & Nyiru Bambu Halus","harga":"Rp 35.000","gambar":"","deskripsi":"Anyaman tampah bambu apus halus untuk menampi beras dan jemur makanan."},{"id":"p3_2","nama":"Keranjang Buah & Hiasan Etnik","harga":"Rp 65.000","gambar":"","deskripsi":"Keranjang bambu motif anyam estetik cocok untuk hampers dan display buah."},{"id":"p3_3","nama":"Paket Besek Bambu Kenduri (10 Pcs)","harga":"Rp 40.000","gambar":"","deskripsi":"Wadah makanan anyaman bambu ramah lingkungan untuk hajatan warga."},{"id":"p3_4","nama":"Kursi Lincak Bambu Santai","harga":"Rp 150.000","gambar":"","deskripsi":"Kursi teras santai dari bambu wulung kokoh dan tahan rayap."}]'::jsonb,
  '[]'::jsonb
),
(
  4,
  'Aneka Hasil Tani & Beras Organik KWT Tajem Asri',
  'Pertanian',
  'KWT Tajem Asri',
  'Dusun Plosorejo, RT 01 / RW 02',
  'Mulai Rp 20.000',
  '6281234567893',
  'Kelompok Wanita Tani Desa Tajemsari yang memproduksi beras putih organik, beras merah sehat, tepung beras alami, serta benih sayuran hidroponik bebas pestisida kimia.',
  '',
  '[{"id":"p4_1","nama":"Beras Putih Organik Tajem 5kg","harga":"Rp 68.000","gambar":"","deskripsi":"Beras putih pulen wangi hasil pertanian organik bebas pupuk kimia sintetis."},{"id":"p4_2","nama":"Beras Merah Sehat Diet 2kg","harga":"Rp 35.000","gambar":"","deskripsi":"Beras merah tinggi serat dan kaya vitamin B untuk pola hidup sehat."},{"id":"p4_3","nama":"Tepung Beras Swadaya 1kg","harga":"Rp 20.000","gambar":"","deskripsi":"Tepung beras giling halus untuk aneka kue tradisional dan jajanan pasar."}]'::jsonb,
  '[]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  nama_produk = EXCLUDED.nama_produk,
  pembuat = EXCLUDED.pembuat,
  dusun = EXCLUDED.dusun,
  harga = EXCLUDED.harga,
  deskripsi = EXCLUDED.deskripsi,
  gambar = EXCLUDED.gambar,
  produk_list = EXCLUDED.produk_list,
  galeri = EXCLUDED.galeri;

-- 6. Seed Destinasi Wisata (Gambar Kosong)
INSERT INTO public.wisata (id, nama_tempat, kategori, lokasi, jam_buka, tiket_masuk, deskripsi, gambar, galeri)
VALUES 
(
  1,
  'Agrowisata Sunset Sawah Tajemsari',
  'Wisata Alam',
  'Dusun Tajemsari RT 02 / RW 01, Tegowanu',
  '06.00 - 18.00 WIB',
  'Gratis',
  'Menawarkan panorama persawahan Tegowanu nan hijau dengan latar belakang matahari terbenam. Dilengkapi gazebo bambu dan spot foto estetik.',
  '',
  '[]'::jsonb
),
(
  2,
  'Taman Edukasi Tani Organik & Lebah',
  'Wisata Edukasi',
  'Kompleks Balai Desa Tajemsari',
  '08.00 - 16.00 WIB',
  'Gratis (Donasi Kebersihan)',
  'Kawasan edukasi pertanian ramah lingkungan, budidaya madu klanceng, serta pembibitan tanaman toga untuk siswa dan wisatawan.',
  '',
  '[]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  nama_tempat = EXCLUDED.nama_tempat,
  deskripsi = EXCLUDED.deskripsi,
  lokasi = EXCLUDED.lokasi,
  gambar = EXCLUDED.gambar,
  galeri = EXCLUDED.galeri;

-- 7. Seed Footer Info
INSERT INTO public.footer_info (id, alamat, telepon, whatsapp, email, jam_pelayanan, maps_url, facebook, instagram, youtube)
VALUES (
  1,
  'Jl. Raya Tajemsari No. 01, Kecamatan Tegowanu, Kabupaten Grobogan, Jawa Tengah 58165',
  '(0292) 7654321',
  '6281234567890',
  'pemdes@tajemsari.desa.id',
  'Senin - Jumat: 08.00 - 15.00 WIB',
  'https://maps.app.goo.gl/3VuZdA1hyBNbtZpn8',
  'https://facebook.com/desatajemsari',
  'https://instagram.com/desatajemsari',
  'https://youtube.com/@desatajemsariofficial'
) ON CONFLICT (id) DO UPDATE SET
  alamat = EXCLUDED.alamat,
  telepon = EXCLUDED.telepon,
  whatsapp = EXCLUDED.whatsapp;

-- 8. Seed Website Settings
INSERT INTO public.website_settings (id, nama_desa, kecamatan, kabupaten, provinsi, email_admin, telepon_kantor, running_text)
VALUES (
  1,
  'Desa Tajemsari',
  'Kecamatan Tegowanu',
  'Kabupaten Grobogan',
  'Jawa Tengah',
  'admin@tajemsari.desa.id',
  '081234567890',
  'Selamat Datang di Website Resmi Desa Tajemsari, Kecamatan Tegowanu, Kabupaten Grobogan. Dapatkan info seputar profil desa, berita pembangunan, agrowisata, dan katalog produk UMKM warga.'
) ON CONFLICT (id) DO UPDATE SET
  nama_desa = EXCLUDED.nama_desa,
  running_text = EXCLUDED.running_text;

-- =========================================================================
-- KETENTUAN STORAGE BUCKET RLS (IZINKAN UPLOAD & AKSES FOTO PUBLIK)
-- =========================================================================
DROP POLICY IF EXISTS "Public Select Storage" ON storage.objects;
DROP POLICY IF EXISTS "Public Upload Storage" ON storage.objects;
DROP POLICY IF EXISTS "Public Update Storage" ON storage.objects;
DROP POLICY IF EXISTS "Public Delete Storage" ON storage.objects;

CREATE POLICY "Public Select Storage" ON storage.objects FOR SELECT USING (bucket_id = 'desa-tajemsari');
CREATE POLICY "Public Upload Storage" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'desa-tajemsari');
CREATE POLICY "Public Update Storage" ON storage.objects FOR UPDATE USING (bucket_id = 'desa-tajemsari');
CREATE POLICY "Public Delete Storage" ON storage.objects FOR DELETE USING (bucket_id = 'desa-tajemsari');
