-- ========================================================
-- SKRIP DATABASE SUPABASE - WEB DESA TAJEMSARI TEGOWANU
-- Execute this script in Supabase Dashboard -> SQL Editor
-- ========================================================

-- 1. TABEL BERITA & PENGUMUMAN
CREATE TABLE IF NOT EXISTS public.berita (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE,
    ringkasan TEXT,
    isi TEXT NOT NULL,
    kategori VARCHAR(50) DEFAULT 'Pembangunan', -- Pembangunan, Kesehatan, Ekonomi, Kegiatan
    gambar TEXT,
    penulis VARCHAR(100) DEFAULT 'Admin Desa Tajemsari',
    tanggal DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. TABEL PERMOHONAN SURAT WARGA (LAYANAN PUBLIK)
CREATE TABLE IF NOT EXISTS public.permohonan_surat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor_tiket VARCHAR(20) UNIQUE NOT NULL,
    nama_warga VARCHAR(150) NOT NULL,
    nik VARCHAR(16) NOT NULL,
    no_hp VARCHAR(20) NOT NULL,
    rt_rw VARCHAR(20) NOT NULL,
    jenis_surat VARCHAR(100) NOT NULL, -- Surat Keterangan Usaha, Domisili, SKTM, dll.
    keperluan TEXT NOT NULL,
    status VARCHAR(30) DEFAULT 'Menunggu' CHECK (status IN ('Menunggu', 'Diproses', 'Selesai', 'Ditolak')),
    catatan_admin TEXT,
    tanggal_pengajuan TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. TABEL POTENSI UMKM DESA
CREATE TABLE IF NOT EXISTS public.umkm (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_produk VARCHAR(150) NOT NULL,
    kategori VARCHAR(50) DEFAULT 'Pertanian', -- Pertanian, Kuliner, Kerajinan, Olahan Madu
    pembuat VARCHAR(100) NOT NULL,
    harga VARCHAR(50),
    deskripsi TEXT,
    wa_seller VARCHAR(20),
    gambar TEXT,
    lokasi VARCHAR(100) DEFAULT 'Desa Tajemsari, Tegowanu',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. TABEL DESTINASI WISATA & POTENSI ALAM
CREATE TABLE IF NOT EXISTS public.wisata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_tempat VARCHAR(150) NOT NULL,
    kategori VARCHAR(50) DEFAULT 'Wisata Alam',
    deskripsi TEXT NOT NULL,
    lokasi VARCHAR(150) NOT NULL,
    jam_buka VARCHAR(100),
    tiket_masuk VARCHAR(50) DEFAULT 'Gratis',
    gambar TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. TABEL PERANGKAT DESA / STRUKTUR ORGANISASI
CREATE TABLE IF NOT EXISTS public.perangkat_desa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama VARCHAR(150) NOT NULL,
    jabatan VARCHAR(100) NOT NULL,
    foto TEXT,
    urutan INT DEFAULT 0
);

-- SEED DATA AWAL (OPTIONAL DATA CONTOH)
INSERT INTO public.berita (judul, slug, ringkasan, isi, kategori, gambar, tanggal) VALUES
('Penyaluran BLT Dana Desa Tajemsari Tahap III', 'blt-tahap-3', 'Pemerintah Desa Tajemsari menyalurkan bantuan langsung tunai kepada 45 KPM secara transparan.', 'Pemerintah Desa Tajemsari Kecamatan Tegowanu Kabupaten Grobogan menyalurkan Bantuan Langsung Tunai (BLT) Dana Desa tahap III tahun anggaran berjalan kepada warga penerima manfaat. Pembagian bertempat di Balai Desa Tajemsari dengan lancar.', 'Ekonomi', 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80', '2026-07-25'),
('Panen Raya Padi Organik Kelompok Tani Tajemsari Makmur', 'panen-raya-padi-organik', 'Petani Desa Tajemsari berhasil meningkatkan produktivitas panen berkat pola tanam ramah lingkungan.', 'Kelompok Tani Tajemsari Makmur merayakan panen raya padi organik di kawasan persawahan Tegowanu. Produktivitas panen naik 15% berkat bimbingan ketahanan pangan dan penggunaan pupuk kompos alami.', 'Pertanian', 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80', '2026-07-18'),
('Pemeriksaan Kesehatan Gratis & Posyandu Balita Tajemsari', 'posyandu-balita-dan-lansia', 'Kader Kesehatan Tajemsari menggelar pemeriksaan tensi, gula darah, serta penimbangan balita.', 'Pemerintah Desa bekerjasama dengan Puskesmas Tegowanu menyelenggarakan Posyandu Balita dan Posbindu Lansia rutin di Balai Desa Tajemsari.', 'Kesehatan', 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80', '2026-07-10');

INSERT INTO public.umkm (nama_produk, kategori, pembuat, harga, deskripsi, wa_seller, gambar) VALUES
('Madu Murni Tajemsari', 'Olahan Madu', 'Pak Warsito', 'Rp 85.000 / 500ml', 'Madu lebah klanceng alami hasil budidaya nektar bunga sekitar desa Tajemsari Tegowanu.', '6281234567890', 'https://images.unsplash.com/photo-1587049352847-4a222e784d38?auto=format&fit=crop&w=800&q=80'),
('Kopi Robusta Sawah Tajem', 'Kuliner', 'Kelompok Usaha Ibu Tani', 'Rp 25.000 / 250gr', 'Biji kopi pilihan diracik khas aroma tradisional Tajemsari, pas ditemani sore di pinggir sawah.', '6281234567891', 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80'),
('Kerajinan Anyaman Bambu Grobogan', 'Kerajinan', 'Mbah Pawiro', 'Rp 35.000 - 150.000', 'Tampah, besek, dan keranjang bambu buatan tangan ramah lingkungan berkualitas eksport.', '6281234567892', 'https://images.unsplash.com/photo-1590736704728-f4730bb30770?auto=format&fit=crop&w=800&q=80');

INSERT INTO public.wisata (nama_tempat, kategori, deskripsi, lokasi, jam_buka, tiket_masuk, gambar) VALUES
('Agrowisata Sunset Sawah Tajemsari', 'Wisata Alam', 'Menyuguhkan pemandangan bentangan sawah hijau yang memanjakan mata dengan spot foto gazebo tradisional.', 'Dusun Tajemsari RT 02 / RW 01, Tegowanu', '06.00 - 18.00 WIB', 'Gratis', 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80'),
('Taman Edukasi Tani Organik', 'Wisata Edukasi', 'Tempat belajar bercocok tanam organik, budidaya madu klanceng, dan hidroponik sederhana.', 'Kompleks Balai Desa Tajemsari', '08.00 - 16.00 WIB', 'Gratis', 'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&w=800&q=80');

-- KETENTUAN ROW LEVEL SECURITY (RLS) - PUBLIC BISA READ, ADMIN BISA READ/WRITE
ALTER TABLE public.berita ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.permohonan_surat ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.umkm ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wisata ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Berita" ON public.berita FOR SELECT USING (true);
CREATE POLICY "Public Read UMKM" ON public.umkm FOR SELECT USING (true);
CREATE POLICY "Public Read Wisata" ON public.wisata FOR SELECT USING (true);
CREATE POLICY "Public Insert Permohonan" ON public.permohonan_surat FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Select Own Permohonan" ON public.permohonan_surat FOR SELECT USING (true);

-- Admin Full Access (If using Supabase Auth authenticated role)
CREATE POLICY "Admin Full Access Berita" ON public.berita FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin Full Access Permohonan" ON public.permohonan_surat FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin Full Access UMKM" ON public.umkm FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin Full Access Wisata" ON public.wisata FOR ALL USING (auth.role() = 'authenticated');
