-- ========================================================
-- SKRIP DATABASE SUPABASE - WEB DESA TAJEMSARI TEGOWANU
-- Execute this script in Supabase Dashboard -> SQL Editor
-- ========================================================

-- 1. TABEL BERITA & PENGUMUMAN (DENGAN SUPPOR MULTIPLE IMAGE GALERI)
CREATE TABLE IF NOT EXISTS public.berita (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE,
    ringkasan TEXT,
    isi TEXT NOT NULL,
    kategori VARCHAR(50) DEFAULT 'Pembangunan', -- Pembangunan, Kesehatan, Ekonomi, Pertanian
    gambar TEXT, -- Cover Image URL
    galeri JSONB DEFAULT '[]'::jsonb, -- Array Gambar Dokumentasi Tambahan
    penulis VARCHAR(100) DEFAULT 'Admin Desa Tajemsari',
    tanggal DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. TABEL PERMOHONAN SURAT WARGA (LAYANAN PUBLIK)
CREATE TABLE IF NOT EXISTS public.permohonan_surat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor_tiket VARCHAR(20) UNIQUE NOT NULL,
    nama_warga VARCHAR(150) NOT NULL,
    nik VARCHAR(16) NOT NULL,
    no_hp VARCHAR(20) NOT NULL,
    rt_rw VARCHAR(20) NOT NULL,
    jenis_surat VARCHAR(100) NOT NULL,
    keperluan TEXT NOT NULL,
    status VARCHAR(30) DEFAULT 'Menunggu' CHECK (status IN ('Menunggu', 'Diproses', 'Selesai', 'Ditolak')),
    catatan_admin TEXT,
    tanggal_pengajuan TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. TABEL POTENSI UMKM DESA
CREATE TABLE IF NOT EXISTS public.umkm (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_produk VARCHAR(150) NOT NULL,
    kategori VARCHAR(50) DEFAULT 'Pertanian',
    pembuat VARCHAR(100) NOT NULL,
    harga VARCHAR(50),
    deskripsi TEXT,
    wa_seller VARCHAR(20),
    gambar TEXT,
    lokasi VARCHAR(100) DEFAULT 'Desa Tajemsari, Tegowanu',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. TABEL DESTINASI WISATA & POTENSI ALAM
CREATE TABLE IF NOT EXISTS public.wisata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_tempat VARCHAR(150) NOT NULL,
    kategori VARCHAR(50) DEFAULT 'Wisata Alam',
    deskripsi TEXT NOT NULL,
    lokasi VARCHAR(150) NOT NULL,
    jam_buka VARCHAR(100),
    tiket_masuk VARCHAR(50) DEFAULT 'Gratis',
    gambar TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- KETENTUAN ROW LEVEL SECURITY (RLS)
ALTER TABLE public.berita ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.permohonan_surat ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.umkm ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wisata ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Berita" ON public.berita FOR SELECT USING (true);
CREATE POLICY "Public Read UMKM" ON public.umkm FOR SELECT USING (true);
CREATE POLICY "Public Read Wisata" ON public.wisata FOR SELECT USING (true);
CREATE POLICY "Public Insert Permohonan" ON public.permohonan_surat FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Select Own Permohonan" ON public.permohonan_surat FOR SELECT USING (true);
